import Navbar from './components/menu.jsx'
import Footer from './components/footer.jsx'

export default function Home() {
  return (
    <>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
              <Navbar/>
              <div style={{height:347}}>
                 <h2>Conteudo da página</h2>
              </div>
              <Footer/>
    </>
  )
}
